### ISSUE TITLE
Bulk Payments - Initial Proposal, High level architecture diagram discussed.

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/design-authority#1]
## **Request**:

**Artifacts**:
- [x] Designs for the PoC - https://github.com/mojaloop/documentation/tree/master/mojaloop-technical-overview/central-bulk-transfers

**Decision(s)**:
- [ ] Actual decision made as a result of discussion

## **Follow-up**:
- [ ] Alternative actions

**Dependencies**:
- [ ] If Applicable

## **Accountability**:
- Owner: @elnyry

**Comment by elnyry** [comment]
The designs for the PoC, have been discussed at the previous Mojaloop convening PI6 as well as in core team and DA meetings. Feedback has been incorporated and designs finalized for the PoC. However, changes are being made as part of implementing the PoC because of the issues identified during implementation.

The actual design will be presented after the PoC which can then be used for a standard implementation.
