### ISSUE TITLE
Standardization and Automation of new DFSP onboarding

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/design-authority#19]
## **Request**:
When re-registering consumers for the "new" DFSPs, note that there is a manual deployment that will need to happen since we are "spinning up" separate instances for each consumer. With new CLI processes, it will give us flexibility if we want to spin up a single handler for Positions for a specific DFSP or if we want that handler to register to all known DFSPs.

**Artifacts**:
- [ ] Artifact to consider [@Contributor]

**Decision(s)**:
- [x] Note that this issue is no longer applicable based on the changes introduced as part of the Performance Optimisation last year November 2018 as the topics are now generic and are not specific to each FSP.

This means that FSP all utilise the same topics but instead are assigned to a specific partition based on the FspID. Thus there is no manual process required to setup/configure pre-requisites for a new FSP other than configuring the prerequisite accounts, limits, callback URIs etc as part of the Central-Ledger Admin API.

If there is any specific action that comes out of this story, then it should be a recommendation/best-practice guide on how to configure mojaloop + kafka with an initial number of partitions to support the scaling requirements. And also if the scaling requirements are over and above the configured partitions, then a guide on how to increase the partitions without impacting the existing ordering of messages.

## **Follow-up**:
- [ ] Alternative actions

**Dependencies**:
- [ ] If Applicable

## **Accountability**:
- Owner: 

## **Notes**:

**Comment by mdebarros** [comment]
Note that this issue is no longer applicable based on the changes introduced as part of the Performance Optimisation last year November 2018 as the topics are now generic and are not specific to each FSP. 

This means that FSP all utilise the same topics but instead are assigned to a specific partition based on the FspID. Thus there is no manual process required to setup/configure pre-requisites for a new FSP other than configuring the prerequisite accounts, limits, callback URIs etc as part of the Central-Ledger Admin API.

If there is any specific action that comes out of this story, then it should be a recommendation/best-practice guide on how to configure mojaloop + kafka with an initial number of partitions to support the scaling requirements. And also if the scaling requirements are over and above the configured partitions, then a guide on how to increase the partitions without impacting the existing ordering of messages.
